// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: WMS_um.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WMSUmClient is the client API for WMSUm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WMSUmClient interface {
	RequestUserIdViaJWTToken(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseCode, error)
}

type wMSUmClient struct {
	cc grpc.ClientConnInterface
}

func NewWMSUmClient(cc grpc.ClientConnInterface) WMSUmClient {
	return &wMSUmClient{cc}
}

func (c *wMSUmClient) RequestUserIdViaJWTToken(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseCode, error) {
	out := new(ResponseCode)
	err := c.cc.Invoke(ctx, "/WMS_um.WMSUm/RequestUserIdViaJWTToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WMSUmServer is the server API for WMSUm service.
// All implementations must embed UnimplementedWMSUmServer
// for forward compatibility
type WMSUmServer interface {
	RequestUserIdViaJWTToken(context.Context, *Request) (*ResponseCode, error)
	mustEmbedUnimplementedWMSUmServer()
}

// UnimplementedWMSUmServer must be embedded to have forward compatible implementations.
type UnimplementedWMSUmServer struct {
}

func (UnimplementedWMSUmServer) RequestUserIdViaJWTToken(context.Context, *Request) (*ResponseCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestUserIdViaJWTToken not implemented")
}
func (UnimplementedWMSUmServer) mustEmbedUnimplementedWMSUmServer() {}

// UnsafeWMSUmServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WMSUmServer will
// result in compilation errors.
type UnsafeWMSUmServer interface {
	mustEmbedUnimplementedWMSUmServer()
}

func RegisterWMSUmServer(s grpc.ServiceRegistrar, srv WMSUmServer) {
	s.RegisterService(&WMSUm_ServiceDesc, srv)
}

func _WMSUm_RequestUserIdViaJWTToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WMSUmServer).RequestUserIdViaJWTToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WMS_um.WMSUm/RequestUserIdViaJWTToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WMSUmServer).RequestUserIdViaJWTToken(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// WMSUm_ServiceDesc is the grpc.ServiceDesc for WMSUm service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WMSUm_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "WMS_um.WMSUm",
	HandlerType: (*WMSUmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestUserIdViaJWTToken",
			Handler:    _WMSUm_RequestUserIdViaJWTToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "WMS_um.proto",
}
